### ISSUE TITLE
gl track .gitignore  (or any file starting with .git) fails with a complaint about paths

### ISSUE THREAD

**Issue by jhbrown94** [sdg-mit/gitless#178]
'gl track' is failing to work on any file prefixed with .git.  This is for 0.8.6, on OS X.  Examples: 
```
$ gl track .gitignore 
✘ path /Users/jhbrown/demo/.gitignore is absolute but should be relative to the repo root

$ gl track .gitx
✘ path /Users/jhbrown/demo/.gitx is absolute but should be relative to the repo root

$ gl track .xgitignore
✔ File .xgitignore is now a tracked file

$ gl --version
GL Version: 0.8.6
You can check if there's a new version of Gitless available at http://gitless.com

$ uname -a
Darwin montrose.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
```

**Comment by docoleman** [comment]
I'd like to take this one. The problematic line is https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L134. I could just append a '/' to repo_dir for the starts with but I think a better condition would be is the file in the `.git` directory, which is what we're actually trying to check.

Further, I'm not sure I understand the else condition. Why return `path` if no one will be able to use it? I think this path is making the error message more confusing to users as well. Maybe it makes sense in the context of the helper functions.

**Comment by docoleman** [comment]
There is a similar condition on https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L121 which would stop someone from tracking a file like `<repo>/.gitfiles/file`. I can apply the same fix to both, because we are very specifically trying not to go in the `.git/` directory exclusively.

**Comment by spderosso** [comment]
> I'd like to take this one. The problematic line is https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L134. I could just append a '/' to repo_dir for the starts with but I think a better condition would be is the file in the .git directory, which is what we're actually trying to check.

Yes, good catch. The use of `startsWith` here is wrong.

> Further, I'm not sure I understand the else condition. Why return path if no one will be able to use it? I think this path is making the error message more confusing to users as well. Maybe it makes sense in the context of the helper functions.

I don't understand it either. This is most likely another bug. One thing I remember is that `PathProcessor` is supposed to always returns paths that are relative to the repo root. The reason why we do that is because libgit2 expects paths relative to the repo root. So there are two things going on here: (1) we should skip `.git`, and (2) all paths we return should be relative to the repo root.

The first `if` seems to be doing the skipping wrong (because it is using [`startsWith`](https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L121)) but the conversion looks fine ([L124](https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L124) & [L132](https://github.com/sdg-mit/gitless/blob/master/gitless/cli/helpers.py#L132)). The second `if` seems to be conflating both (1) and (2) and not doing either one correctly.

**Comment by docoleman** [comment]
Got it! I did some research and it seems like this is a tricky thing to get right (surprise!). [Here is a fun summary](https://stackoverflow.com/questions/3812849/how-to-check-whether-a-directory-is-a-sub-directory-of-another-directory).

I'll try one of the simpler methods and get a fix up.
