### ISSUE TITLE
When creating a branch and switching to it you lose all ignored files

### ISSUE THREAD

**Issue by Erikvv** [sdg-mit/gitless#60]
Steps to reproduce with my repository:

- add a folder to .gitignore, and create some files in it
- gl branch -c feature/mybranch
- gl switch feature/mybranch
- the files are gone

It seems the files are stashed. Perhaps the unstash failed for some reason? Because the file was automatically recreated in the mean time? There is no error indicating anything went wrong.

**Comment by spderosso** [comment]
When you switch back to the original branch you don't see them anymore?  Not seeing the ignored files when you switch to `feature/mybranch` is expected behavior since they were not created in `feature/mybranch`. You should see the files when you switch back to the original branch, but let me know if that's not the case.

In Gitless, each branch keeps its working version of files separate from each other.
