### ISSUE TITLE
Current branch shortcut

### ISSUE THREAD

**Issue by ns-cweber** [sdg-mit/gitless#76]
For arguments that take branch names, it would be useful to support a shortcut to refer to the current branch. For example, `gl history -b .` or `gl branch -d .`.

**Comment by spderosso** [comment]
`gl history` defaults to the current branch if no value for `-b` is given (so instead of doing `gl history -b .` you can do `gl history`). And you can't delete the branch you are on (so `gl branch -d .` would have no effect).

I don't see the use of having a shortcut for the current branch, since most commands default to using the the current branch if none is given as input. But if you have other situations in which having a shortcut would be useful, feel free to reopen this issue.
