### ISSUE TITLE
Crash instructions refer to website, but it doesn't contain bug reporting info.

### ISSUE THREAD

**Issue by chrish42** [sdg-mit/gitless#89]
When `gl` prints a backtrace, gitless refers to http://gitless.com/ for instructions on how to report bugs. However, there's not sign on that webpage of instructions to report bugs.

**Comment by docoleman** [comment]
I can add something to handle this. @spderosso I can go very simple, with just a link to the [issues page](https://github.com/sdg-mit/gitless/issues/) on github or more complicated, like an entire section in the page. Here's one possibility:
![Screenshot from 2019-09-23 09-43-05](https://user-images.githubusercontent.com/5830834/65430858-985da000-dde6-11e9-8fef-1713b9c600b2.png)

**Comment by spderosso** [comment]
Thanks for looking into this issue. I like the idea of having just a link to the issues page. You can put it above "about". Perhaps so that the bug report link doesn't look too alone we can add links to the other sections of the page:

documentation | gitless vs git | report a bug

what do you think?

**Comment by docoleman** [comment]
Yeah, I was really trying to fill it out. I think the header links look good. Here's my favorite:
![Screenshot from 2019-09-23 16-28-56](https://user-images.githubusercontent.com/5830834/65460229-75031700-de1f-11e9-90a8-f73a831037f7.png)

**Comment by spderosso** [comment]
lgtm!
